# Site settings
title: Hackathonukah - The Hackathon of Lights
email: hackathonukah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackathonukah.com" # the base hostname & protocol for your site
twitter_username: hackathonukah
github_username:  hackathonukah

# Build settings
markdown: redcarpet
highlighter: pygments

# SASS settings
sass:
    sass_dir: _sass
